name: "Build"
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm i
          npm build
          npm test
      - uses: codecov/codecov-action@v1
      - id: main
        name: Test Action - main
        uses: ./
        with: 
          keys: |
            main
      - id: foobar
        name: Test Action - foobar
        uses: ./
        with: 
          keys: |
            foobar
        continue-on-error: true
      - name: assert foobar failed
        if: steps.foobar.outcome != 'failure'
        run: |
          echo "foobar unexpectedly succeeded"
          exit 1
      - run: touch bar.js      
      - id: bar
        name: Test Action - bar
        uses: ./
        with: 
          keys: |
            bar
        continue-on-error: true
      - name: assert bar failed
        if: steps.bar.outcome != 'failure'
        run: |
          echo "bar unexpectedly succeeded"
          exit 1
      - id: baz
        name: Test Action - baz
        uses: ./
        with: 
          keys: |
            baz
        continue-on-error: true
      - name: assert baz failed
        if: steps.baz.outcome != 'failure'
        run: |
          echo "baz unexpectedly succeeded"
          exit 1
